### ISSUE TITLE
add list.txt 

### ISSUE THREAD

**Issue by 231351** [bartobri/bitcoin-toolkit#3]
add feature like with this `echo " string" | btk privkey -s` command  to `echo "C:/user/path/list.txt" | btk privkey -s` 

so i can use my list.txt with this

**Comment by bartobri** [comment]
The path you listed is a windows path. My program is not supported on windows platforms. To do this on unix use the cat command: `cat /path/to/my/file.txt | btk privkey -b`

Also, I provide an example on the main readme page for generating private keys from entire files. In that example I use the -b switch, which is better for entire files. The -s switch is just for strings and I don't think it'll read past the first newline character it encounters.
